-- Script documental. No se ejecuta automáticamente; application.yml mantiene ddl-auto: update.
CREATE TABLE IF NOT EXISTS simulations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name VARCHAR(150) NOT NULL,
    loan_amount NUMERIC(15, 2) NOT NULL,
    interest_rate NUMERIC(5, 2) NOT NULL,
    term_months INTEGER NOT NULL,
    monthly_payment NUMERIC(15, 2) NOT NULL,
    total_interest NUMERIC(15, 2) NOT NULL,
    total_payment NUMERIC(15, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
